=== Appendium/flatpack/flatpack/src/main/java/net/sf/flatpack/xml/flatpack.dtd
<?xml version="1.0" encoding="UTF-8"?>
<!ELEMENT PZMAP (RECORD*,COLUMN+,RECORD*)>
    <!ELEMENT RECORD (COLUMN+)>
    <!ATTLIST RECORD id ID #REQUIRED
    		  startPosition CDATA  "1"
			  endPosition CDATA "1"
              elementNumber CDATA "1"
              elementCount CDATA "0"
              indicator CDATA "">
	<!ELEMENT COLUMN EMPTY>
	<!ATTLIST COLUMN name CDATA  #REQUIRED
			  length CDATA  "1"	>

=== Appendium/flatpack/flatpack/src/test/resources/test-complex-fixed.xml
<?xml version='1.0'?>
<!DOCTYPE PZMAP SYSTEM "flatpack.dtd" >
<PZMAP>
    <RECORD id="header" startPosition="1" endPosition="2" indicator="HI">
        <COLUMN name="HeaderRecordType" length="2" />
        <COLUMN name="FileIdentifier" length="4" />
        <COLUMN name="TradeDate" length="8" />
        <COLUMN name="NumberOfRecords" length="7" />
        <COLUMN name="FileSignatures" length="40" />
        <COLUMN name="TradingStatus" length="2" />
        <COLUMN name="Dummy" length="18" />
    </RECORD>
    <RECORD id="exchange" startPosition="1" endPosition="2" indicator="TE">
        <COLUMN name="RecordType" length="2" />
        <COLUMN name="StatusIndicator" length="1" />
        <COLUMN name="ExchangeCode" length="8" />
        <COLUMN name="ExchangeName" length="259" />
    </RECORD>
    <RECORD id="country" startPosition="1" endPosition="2" indicator="XC">
        <COLUMN name="RecordType" length="2" />
        <COLUMN name="StatusIndicator" length="1" />
        <COLUMN name="ExchangeCode" length="8" />
        <COLUMN name="CountryName" length="50" />
        <COLUMN name="CountryCode" length="209" />
    </RECORD>
    <COLUMN name="ignoramus" length="270"/>
</PZMAP>

=== Appendium/flatpack/flatpack-samples/src/main/script/PEOPLE-DelimitedWithHeaderTrailer.pzmap.xml
<?xml version='1.0'?>
<!-- DTD can be pulled from the Jar or over the web-->
<!DOCTYPE PZMAP SYSTEM	"flatpack.dtd" >
<!--<!DOCTYPE PZMAP SYSTEM	"http://flatpack.sourceforge.net/flatpack.dtd" >-->
<PZMAP>
    <RECORD id="header" indicator="H" elementNumber="1">
        <COLUMN name="RECORDINDICATOR" />
        <COLUMN name="HEADERDATA" />
    </RECORD>
	<COLUMN name="FIRSTNAME" />
	<COLUMN name="LASTNAME" />
	<COLUMN name="ADDRESS" />
	<COLUMN name="CITY" />
	<COLUMN name="STATE" />
	<COLUMN name="ZIP" />
    <RECORD id="trailer" indicator="T" elementNumber="1">
        <COLUMN name="RECORDINDICATOR" />
        <COLUMN name="TRAILERDATA" />
    </RECORD>
		
</PZMAP>

=== Appendium/flatpack/flatpack-samples/src/main/script/PEOPLE-FixedLengthWithHeaderTrailer.pzmap.xml
<?xml version='1.0'?>
<!-- DTD can be pulled from the Jar or over the web-->
<!DOCTYPE PZMAP SYSTEM	"flatpack.dtd" >
<!--<!DOCTYPE PZMAP SYSTEM	"http://flatpack.sourceforge.net/flatpack.dtd" >-->

<PZMAP>
    <RECORD id="header" startPosition="1" endPosition="7" indicator="HEADER ">
        <COLUMN name="INDICATOR" length="7" />
	    <COLUMN name="HEADERDATA" length="19" />
    </RECORD>
	<COLUMN name="FIRSTNAME" length="35" />
	<COLUMN name="LASTNAME" length="35" />
	<COLUMN name="ADDRESS" length="100" />
	<COLUMN name="CITY" length="100" />
	<COLUMN name="STATE" length="2" />
	<COLUMN name="ZIP" length="5" />
    <RECORD id="trailer" startPosition="1" endPosition="7" indicator="TRAILER">
        <COLUMN name="INDICATOR" length="7" />
	    <COLUMN name="TRAILERDATA" length="19" />
    </RECORD>
		
</PZMAP>
